times=('Atlético-MG','Palmeiras','Flamengo','Bragantino','Fortaleza','Corinthians','Internacional','Fluminense','América Mineiro','Cuiabá','Atlético-GO','São Paulo','Ceará','Athletico-PR','Santos','Bahia','Sport','Juventude','Grêmio','Chapecoense')
print('todos os times:')
print(times)
print('cinco primeiros colocados:')
cinco=(times[0:6])
print(cinco)
print('ultimos 4 colocados:')
colocação=(times[15:19])
print(colocação)
print('times organizados em ordem alfabética')
organização=sorted(times)
print(organização)
print('colocação da chapecoense')
chape=(times.index('Chapecoense'))
print(chape)

